<header class="main-header">
  <a href="menu.php" class="logo">
    <!-- LOGO -->
    <i class="glyphicon glyphicon-cog"></i>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!--Boton Menu -->
    <a class="sidebar-toggle" role="button" data-toggle="offcanvas" href="#">
       <i class="glyphicon glyphicon-menu-hamburger"></i>

    </a>

    <!-- Navbar Right Menu -->

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown user user-menu">
<a href="php/cerrar-sesion.php">Salir</a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li

            </li>
            <!-- Menu Footer-->
            <li class="user-footer">

          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
             <!-- imagen del usuario -->
            </div>
<!--Boton cerrrar-->
          </div>
          <!-- AQUI COMIENZA EL MENU -->
          <ul class="sidebar-menu">
              <li class="header">PANEL DE NAVEGACION</li>
                <!--TIEMPO EXTRA-->

                <!--Añadir-->
                <li class="treeview">
                  <a href="nuevaFicha.php">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Nueva Ficha</span>
                    <!-- <i class="fa fa-angle-left pull-right"></i> -->
                  </a>
                  <!-- <ul class="treeview-menu">
                    <li><a href="consultaExamen.php"><i class="fa fa-circle-o text-orange"></i> Consultar Examen Físico</a></li>
                  </ul> -->
                </li>
                <!--Busqueda-->
                <li class="treeview">
                  <a href="busquedaFicha.php">
                    <i class="glyphicon glyphicon-search"></i>
                    <span>Busqueda</span>
                    <!-- <i class="fa fa-angle-left pull-right"></i> -->
                  </a>
                  <!-- <ul class="treeview-menu">
                    <li><a href="consultaExamen.php"><i class="fa fa-circle-o text-orange"></i> Consultar Examen Físico</a></li>
                  </ul> -->
                </li>


          </ul>

        </section>
        <!-- /.sidebar -->
      </aside>
